debug: false
management.endpoints.web.exposure.include: "*" # spring Boot Actuator의 모든 엔드포인트를 웹에서 노출


logging:
  level:
    com.myproject.board: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
    url: jdbc:mysql://localhost:3306/board
    username: jinhak
    password: 9943
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true # data.sql가 실행
    hibernate.ddl-auto: create # DB 자동 초기화
    # create : 기존 테이블 삭제 후 새로운 테이블 생성(개발)
    # create-drop : create와 동일. 단, 종료시 테이블 삭제(개발)
    # update : 기존 테이블을 삭제하지 않고, 변경 사항(컬럼 추가)만 적용(개발)
    # validate : 엔티티와 테이블의 매핑 확인(운영)
    # none : 사용하지 않음(운영)
    show-sql: true    # 쿼리를 콘솔에 출력하게
    properties:
      hibernate.format_sql: true # 콘솔에 출력되는 쿼리를 보기 좋게 포맷팅
      hibernate.default_batch_fetch_size: 100
      h2.console.enabled: false
  sql.init.mode: always
  data.rest:
    base-path: /api
    detection-strategy: annotated
  thymeleaf3:
    decoupled-logic: true




